refactor/fixes
Qbox-project/qbx-mechanicjob pull request #13
Opened 2023-07-19 21:30 UTC by buddizer

## Description

- Fixed detaching vehicle not allowing to attach again
- Converted stash to ox_inventory stash (loaded on resourcestart)
- Corrected target locations to be able to use them

## Checklist

- [x] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [x] My code fits the style guidelines.
- [x] My PR fits the contribution guidelines.

2023-07-19 22:00 UTC, D4isDAVID requested changes

2023-07-21 07:35 UTC, Manason approved these changes

2023-07-21 11:54 UTC, D4isDAVID requested changes

2023-07-21 11:54 UTC, D4isDAVID commented on fxmanifest.lua
> +    'locales/es.lua',
```suggestion
    'locales/en.lua',
```
Default language should be English

2023-07-23 12:22 UTC, merged